name: python-safety-check
on:
  push:
    branches:
      - main
env:
  DEP_PATH: src/requirements.txt

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: aufdenpunkt/python-safety-check@v2